### PR TITLE
fixed git-flow issue

### PR DESCRIPTION
**Pull request by cornets28**

### CODE REVIEW

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
Hello @CornetS28 ✋ 

Nice work but you still need to improve some 😄 .

- [x] Remove all the console.log

- [x] make your readme little bit more descriptive 

- [ ] It has error handling for promises or async/await

- [x]  usage of arrow functions instead of the `function` keyword

- [ ] It has a toggle control to determine if the result will be shown in Celsius or Fahrenheit 

- [ ] It changes its appearance based on the received data

- [x] [OPTIONAL] add "webpack-dev-server" package 

Please make those changes and submit for another review

Happy Coding

**Comment by CornetS28** [comment]
The site I am using to collect data for its API does not provide any data for Fahrenheit. Therefore, there is no need to set a toggle control to determine if the result will be shown in Celsius or Fahrenheit.

**Comment by AdnanAfsari** [comment]
Hello @CornetS28 ✋ 

Nice try but you still have to make some improvement 😄 .

- [ ] You have to convert your temperature to Fahrenheit manually ,like this.Search on google you will get lots of examples.
`const fahrenheit = Math.round((temp - 273.15) * 9/5 + 32);`

- [ ] It changes its appearance based on the received data.You should change the look of the page based on the data, maybe by changing the color of the background or by adding images that describe the weather. (You could even use the Giphy API to find appropriate weather-related gifs and display them).

Please make those changes and submit for another review 💪 .

Happy Coding

**Comment by AdnanAfsari** [comment]
Hello @CornetS28 ✋ 

its really required that your app should change appearance based on data.
I think it will be easier for you now to think after our conversation.if you are still confused reach out to someone or Fulltime TSEs 😄 .

Happy Coding

**Comment by AdnanAfsari** [comment]
Hello @CornetS28 ✋ 

Nice work and improvement man, I really appreciate that 👏 .You still have to make some minor fix 😫 .

- [ ] It does not show the input filed when i first load the page, i had to press clear button to get that.
Screenshot 2019-10-05 at 4 19 15 PM

- [ ] Its nice that you managed to get those icons based on weather condition but there is small problem.When i add new city it does not get cleared up and it keep adding one after another.
Screenshot 2019-10-05 at 4 18 19 PM

- [ ] Its nice that we are also getting in Fahrenheit but it will be even better if you can implement a toggle button to show it back and forth.

Please make those improvement and submit for another review 😄 .

Happy Coding

**Review by AdnanAfsari — APPROVED** [review]
Hello @CornetS28 ✋ 

Nice improvement 👏 .Its a 👍 from me.

Happy Coding

**Pull request merged**
